var myName="pooja";
var age=22;
var marrital_status=false;
var city="pune";
console.log(myName);
console.log(age);
console.log(city);
console.log(marrital_status);
console.log("**************************");
console.log(typeof myName);
console.log(typeof marrital_status);
console.log(typeof age);
console.log(typeof city);
var my_project_name;
console.log("**************************");
console.log(my_project_name);
console.log("****************************");
var my_properties=null;
console.log(my_properties);